name: Deploy to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to SFTP server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ftp.cluster100.hosting.ovh.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "."
        target: "/home/fastfoq/soulmade"
        strip_components: 0
        rm: true
        exclude: |
          .git*
          .github*
